[
  {
    "output": "",
    "console": [
      "running internal tests\n"
    ],
    "status": "idle"
  },
  {
    "output": "<pre style='font-size: 12px'>15</pre>",
    "console": [
      "internal error\n"
    ],
    "status": "idle"
  },
  {
    "output": [
      {
        "msg": "This cell raised an exception: ValueError('Failed to authenticate. The correct password is 's3cret'.')",
        "exception_type": "ValueError",
        "raising_cell": null,
        "type": "exception"
      }
    ],
    "console": [
      "<span class=\"codehilite\"><div class=\"highlight\"><pre><span></span><span class=\"gt\">Traceback (most recent call last):</span>\n  &quot;</span>, line <span class=\"m\">3</span>, in <span class=\"n\">&lt;module&gt;</span>\n<span class=\"w\">    </span><span class=\"k\">raise</span> <span class=\"ne\">ValueError</span><span class=\"p\">(</span>\n<span class=\"gr\">ValueError</span>: <span class=\"n\">Failed to authenticate. The correct password is &#39;s3cret&#39;.</span>\n</pre></div>\n</span>"
    ],
    "status": "idle"
  }
]